### ISSUE TITLE
problem with the darwin binary of prometheus_demo_service

### ISSUE THREAD

**Issue by litvos** [juliusv/prometheus_demo_service#1]
Hi,

after downloading prometheus_demo_service-0.0.4.darwin-amd64.tar.gz binary result file is not startable on the OSX (10.11).

$ file ./prometheus_demo_service
./prometheus_demo_service: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), not stripped

$ cksum prometheus_demo_service
3938885981 10159752 prometheus_demo_service

**Comment by juliusv** [comment]
Thank you for pointing this out! I must have botched the cross-compile back then. I uploaded a new set of binaries which should hopefully be correct now.
