### ISSUE TITLE
feat: Darwin release

### ISSUE THREAD

**Issue by jotadrilo** [juliusv/prometheus_demo_service#3]
Hello!

Thanks for building this service for demo purposes!

Would you mind building the Go binary for Darwin arch? I am running the LFS241 course (monitoring system and services with Prometheus) on a macOS laptop and it would very useful to have a link under the [Releases](https://github.com/juliusv/prometheus_demo_service/releases) section.

I know the course is meant to be run in a Linux environment but using macOS is a valid option since we are working with Go and Python tools.

Otherwise, I suggest adding a `go.mod` file to the project to ease building it for macOS users:

```shell
module github.com/juliusv/prometheus_demo_service

go 1.15

require github.com/prometheus/client_golang v1.8.0
```

**Comment by juliusv** [comment]
Thanks for the idea, I added a small crossbuild script and attached binaries (no .tar.gz this time since it's just a single binary) for lots of archs/OSes for the latest release: https://github.com/juliusv/prometheus_demo_service/releases/tag/0.7.0
